### ISSUE TITLE
Sphinx 2.0 crashes with exception: 'Sphinx' object is not iterable

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinx-needs#1074]
NOTE: Since I found out the crash is caused by a not-yet updated internal sphinx-needs API function usage, you can close this. I'll leave the rest of the text for reference if others experience the same problem.

## Problem

When running sphinx-build on a project that uses sphinx plug-ins to create needs (I'll send you the details per PN @danwos ), I get the following abort when running `sphinx-build -b inventories` (note: the inventories builder is a builder by a small internal extension that is used to generate needs.json and object.inv without executing the sphinx write phase):

```

Traceback (most recent call last):
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/builder.py", line 136, in build_needs_json
    needs_builder.finish()
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/builder.py", line 56, in finish
    post_process_needs_data(self.app)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/debug.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/directives/need.py", line 377, in post_process_needs_data
    resolve_dynamic_values(needs, app)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/functions/functions.py", line 208, in resolve_dynamic_values
    func_call, func_return = _detect_and_execute(element, need, app)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/functions/functions.py", line 310, in _detect_and_execute
    func_return = execute_func(app, need, func_call)  # Execute function call and get return value
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/functions/functions.py", line 76, in execute_func
    func_return = func(app, need, SphinxNeedsData(app.env).get_or_create_needs(), *func_args, **func_kwargs)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/debug.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/src/tools/documentation/src/sphinx_conf/needs/dynamic_functions.py", line 161, in copy_list
    result = filter_needs(app, needs.values(), filter, need)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/debug.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/filter_common.py", line 284, in filter_needs
    for filter_need in needs:
TypeError: 'Sphinx' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx/application.py", line 349, in build
    self.events.emit('build-finished', None)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function build_needs_json at 0x7f34d4a49630> for event 'build-finished' threw an exception (exception: 'Sphinx' object is not iterable)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/builder.py", line 136, in build_needs_json
    needs_builder.finish()
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/builder.py", line 56, in finish
    post_process_needs_data(self.app)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/debug.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/directives/need.py", line 377, in post_process_needs_data
    resolve_dynamic_values(needs, app)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/functions/functions.py", line 208, in resolve_dynamic_values
    func_call, func_return = _detect_and_execute(element, need, app)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/functions/functions.py", line 310, in _detect_and_execute
    func_return = execute_func(app, need, func_call)  # Execute function call and get return value
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/functions/functions.py", line 76, in execute_func
    func_return = func(app, need, SphinxNeedsData(app.env).get_or_create_needs(), *func_args, **func_kwargs)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/debug.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/src/tools/documentation/src/sphinx_conf/needs/dynamic_functions.py", line 161, in copy_list
    result = filter_needs(app, needs.values(), filter, need)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/debug.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx_needs/filter_common.py", line 284, in filter_needs
    for filter_need in needs:
TypeError: 'Sphinx' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx/application.py", line 355, in build
    self.events.emit('build-finished', err)
  File "/home/user/workspace/.sphinx-venv/lib/python3.10/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function build_needs_json at 0x7f34d4a49630> for event 'build-finished' threw an exception (exception: 'Sphinx' object is not iterable)

Extension error (sphinx_needs.builder):
Handler <function build_needs_json at 0x7f34d4a49630> for event 'build-finished' threw an exception (exception: 'Sphinx' object is not iterable)
```

Full command line:

`~/workspace/src$ sphinx-build -M inventories . ../build/ -c doc -v -W -w ../logs/sphinx_build_inventories_warnings.log -j auto`

The error also appears with `-j 1`.

OS: Linux (Ubuntu 22.04)
python version: 3.10.12

installed pip packages:

```
Sphinx==6.1.3
mdformat_myst==0.1.5
myst-parser==1.0.0
doxysphinx==3.3.7
sphinx-autoapi==3.0.0
sphinx-bernard-theme==0.1.12
sphinx-copybutton==0.5.2
sphinx-data-viewer==0.1.2
sphinx-docxbuilder==2019.1.28.post1
sphinx-needs==2.0.0
sphinx-rtd-theme==1.3.0
sphinx-warnings-filter==0.2.1
sphinx_design==0.5.0
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-bibtex==2.5.0
sphinxcontrib-confluencebuilder==2.3.0
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-doxylink==1.12.3
sphinxcontrib-excel-table-plus==1.0.8.2
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-inlinesyntaxhighlight==0.2
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-mermaid==0.9.2
sphinxcontrib-moderncmakedomain==3.25.0
sphinxcontrib-plantuml==0.27
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
```

## Solution

We stumbled upon a change in the internal sphinx-needs API: The filter_needs function signature was changed and our dynamic function used in this project is not adapted yet.

This is the dynamic function that you see appearing in the call stack:

```
def copy_list(app, need, needs, filter, option="id"):  # pylint: disable=redefined-builtin
    """Copies the option values of multiple needs to another need option as list.

    This function is useful to bulk link a need to multiple other needs by copying
    the ids of the needs to a (extra-)link option of the target need.
    Full documentation of filter strings:
    https://sphinxcontrib-needs.readthedocs.io/en/latest/filter.html#filter-string

    :param option: name of the option to copy, defaults to the ID of the source needs
    :param filter: a sphinx needs filer string, which results are used as copy source.
    :return: list of copied need options
    """

    filtered_needs = []
    if filter:
        result = filter_needs(app, needs.values(), filter, need)
        if result:
            filtered_needs = result

    res = []
    for filtered_need in filtered_needs:
        res.append(filtered_need[option])

    return res
```

**Comment by chrisjsewell** [comment]
> internal sphinx-needs API function usage

Yep thanks for noting @arwedus, indeed the signature of `filter_needs` has changed, to make the inputs more "specific" (rather than parsing the whole sphinx application).
I hope just a matter of changing your code a little 😄
