### ISSUE TITLE
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: NeedOutgoing

### ISSUE THREAD

**Issue by aanagnosastronauticscom** [useblocks/sphinx-needs#1210]
I strongly suspect this is related to an old bug #796 

# Description
I am using a custom directive in order to parse needs out of the comments of files.
So i am creating needs using the `add_need` function.
These programmatically created needs are the **only** needs in the .rst file.

When i go to `make needs` things work fine
`make singlehtml` fine
`make simplepdf` fine
`make html` i get the error.

# Observations
If i create a simple need in the same .rst file that has the directive:
```
 .. need:: the need
   :id: THE_NEED_999
```
Then the error will go away and things work as expected.

# Error message
```
/work/doc/svcp/source/scenarios.rst:2: WARNING: unknown node type: <NeedOutgoing: <inline...>>

Exception occurred:
  File "/usr/local/lib/python3.12/site-packages/docutils/nodes.py", line 2027, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: NeedOutgoing
The full traceback has been saved in /tmp/sphinx-err-7mq87370.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: html] Error 2
```

# Traceback
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/sphinx/cmd/build.py", line 337, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/local/lib/python3.12/site-packages/sphinx/application.py", line 378, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/usr/local/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 367, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 614, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 624, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/local/lib/python3.12/site-packages/sphinx/builders/html/__init__.py", line 660, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/local/lib/python3.12/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/local/lib/python3.12/site-packages/sphinx/writers/html.py", line 36, in translate
    self.document.walkabout(visitor)
  File "/usr/local/lib/python3.12/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 10 more times]
  File "/usr/local/lib/python3.12/site-packages/docutils/nodes.py", line 199, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/local/lib/python3.12/site-packages/sphinx/util/docutils.py", line 636, in dispatch_departure
    super().dispatch_departure(node)
  File "/usr/local/lib/python3.12/site-packages/docutils/nodes.py", line 2005, in dispatch_departure
    return method(node)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/docutils/nodes.py", line 2027, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: NeedOutgoing
```

 # packages and versions
```
alabaster==0.7.16
attrs==23.2.0
Babel==2.15.0
beautifulsoup4==4.12.3
Brotli==1.1.0
certifi==2024.7.4
cffi==1.16.0
charset-normalizer==3.3.2
contourpy==1.2.1
cssselect2==0.7.0
cycler==0.12.1
docutils==0.21.2
fonttools==4.53.1
html5lib==1.1
idna==3.7
ijson==3.3.0
imagesize==1.4.1
iniconfig==2.0.0
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
libsass==0.23.0
MarkupSafe==2.1.5
matplotlib==3.9.1
numpy==2.0.1
packaging==24.1
pillow==10.4.0
pluggy==1.5.0
pycparser==2.22
pydyf==0.11.0
Pygments==2.18.0
pyparsing==3.1.2
pyphen==0.15.0
pytest==8.3.2
python-dateutil==2.9.0.post0
referencing==0.35.1
requests==2.32.3
requests-file==1.5.1
rpds-py==0.19.1
setuptools==71.1.0
six==1.16.0
snowballstemmer==2.2.0
soupsieve==2.5
Sphinx==7.4.7
sphinx-data-viewer==0.1.4
sphinx-needs==2.1.0
sphinx-simplepdf @ file:///sphinx-simplepdf/sphinx-simplepdf-main
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-plantuml==0.30
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
tinycss2==1.3.0
urllib3==2.2.2
weasyprint==62.3
webencodings==0.5.1
wheel==0.43.0
zopfli==0.2.3
```

**Comment by chrisjsewell** [comment]
Heya, all internal directives use the `add_doc` function, to record documents that will require post-processing: https://github.com/useblocks/sphinx-needs/blob/affe6be44cff390415e40c4c8a23999349d9d732/sphinx_needs/utils.py#L635

It's of note that "technically" this is not currently part of the public API 😬 
but yeh this is the only way at present I believe, if you are using custom directives

**Comment by aanagnosastronauticscom** [comment]
`add_doc` appears to be safe against multiple additions so i just called it from the directives run function.
It does appear to resolve the issue i was having.
It may not be a public part of the public API but its still cleaner then the junk needs i was creating to resolve it before.
