### ISSUE TITLE
Request: improved error messages from custom python functions

### ISSUE THREAD

**Issue by AlexanderLanin** [useblocks/sphinx-needs#779]
# current state

Within `needs_render_context` we can pass custom python functions to jinja to be called when the template is rendered. When such a function throws an exception, only the exception text is printed which is quite often not enough to trace it back to something specific.

(Pseudocode) example of conf.py:
```py
def my_function():
  print(txt)

needs_render_context = {"my_function": my_function}
```

And what I get is:
```py
Extension error (sphinx_needs.directives.needuml):
Handler <function process_needuml at 0x7fb0c7b6ae60> for event 'doctree-resolved' threw an exception (exception: local variable 'txt' referenced before assignment)
```

In this case I'm lucky since I can search for 'txt' in my custom functions.

# desired state
- Print more information which will help fix the warning (file:line or full call stack)
- Instead of cryptic needuml extension error, print something like "exception in needs_render_context function"

# current workaround
Instead of adding `my_function` to `needs_render_context`, I'm adding a wrapper:

```py
def my_function_wrapper():
    try:
        return my_function()
    except Exception as e:
        logging.exception(
            f"Error in my_function()", exc_info=e
        )
        # Stop all other output immediately. We want the error to be readable!
        sys.exit(1)
```

# implementation ideas
by @PhilipPartsch 
- wrap this in a try catch call and print pretty error messages
  https://github.com/useblocks/sphinx-needs/blob/d9a0d32ffe9cfdafb306be62a842f96cc8990d68/sphinx_needs/directives/needuml.py#L209
- instead of just passing custom functions, wrap them in try catch wrappers in https://github.com/useblocks/sphinx-needs/blob/d9a0d32ffe9cfdafb306be62a842f96cc8990d68/sphinx_needs/directives/needuml.py#L193

**Comment by AlexanderLanin** [comment]
Here is a better hack until this is improved (I'm no python expert, but this seems to work fine):

```py
def exit_on_exception(func):
    """Wrap any python function to make it print exceptions and exit immediately."""

    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except Exception as e:
            logger.exception(f"Error in {func.__name__}(...)", exc_info=e)
            # Stop all other output immediately. We want the error to be readable!
            sys.exit(1)

    return wrapper


@exit_on_exception
def my_function():
  print(txt)
```

**Comment by danwos** [comment]
I agree, that this is suboptimal, but a wanted behavior by Sphinx (afaik).
To get the error and the traceback behind the not-helpful event-handler exception, you can use the verbose mode of sphinx ``-v`` --> ``sphinx-build -v -b HTML . _build/html``.

Wouldn't this be enough?

**Comment by AlexanderLanin** [comment]
Well sphinx is not made for end users writing python functions as we do with `needs_render_context`

**Comment by AlexanderLanin** [comment]
With -v we do get more info! But not nearly as pretty as with `exit_on_exception`.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/local/lib/python3.10/dist-packages/sphinx_needs/directives/needuml.py", line 380, in process_needuml
    puml_node = transform_uml_to_plantuml_node(
  File "/usr/local/lib/python3.10/dist-packages/sphinx_needs/directives/needuml.py", line 143, in transform_uml_to_plantuml_node
    (uml_content_return, processed_need_ids_return) = jinja2uml(
  File "/usr/local/lib/python3.10/dist-packages/sphinx_needs/directives/needuml.py", line 206, in jinja2uml
    uml = mem_template.render(**data)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
[!!! interesting part stats here !!!]
  File "/workspaces/testing/conf.py", line 548, in draw_deployment
    print(txt)
NameError: name 'txt' is not defined
[!!! interesting part ends here !!!]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sphinx/cmd/build.py", line 281, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/local/lib/python3.10/dist-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.10/dist-packages/sphinx/builders/__init__.py", line 310, in build_update
    self.build(to_build,
  File "/usr/local/lib/python3.10/dist-packages/sphinx/builders/__init__.py", line 376, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.10/dist-packages/sphinx/builders/__init__.py", line 571, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/lib/python3.10/dist-packages/sphinx/builders/__init__.py", line 578, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/local/lib/python3.10/dist-packages/sphinx/environment/__init__.py", line 591, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/usr/local/lib/python3.10/dist-packages/sphinx/environment/__init__.py", line 642, in apply_post_transforms
    self.events.emit('doctree-resolved', doctree, docname)
  File "/usr/local/lib/python3.10/dist-packages/sphinx/events.py", line 105, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function process_needuml at 0x7f94cc3e3910> for event 'doctree-resolved' threw an exception (exception: name 'txt' is not defined)

Extension error (sphinx_needs.directives.needuml):
Handler <function process_needuml at 0x7f94cc3e3910> for event 'doctree-resolved' threw an exception (exception: name 'txt' is not defined)
```

**Comment by ubmarco** [comment]
Btw, to debug the custom functions, you can also run
`sphinx-build -b HTML . _build/html` in a Debugger and set a (conditional) breakpoint in your custom function.
Helpful during development phase.

**Comment by danwos** [comment]
As we are only an extension, I don't want to support extension-specific error handling here.
For me, this is more of a question for Sphinx to provide a better logger.
And with `-v` you get all information, which are needed or available.

Custom outputs just for this extension may also break others' workflow if they need the standard python way of presenting errors (e.g. because they parse the logs for the CI.)

**Comment by danwos** [comment]
Got convinced to add additional output (source and co.) to the eception chain.
But I would like to use then the normal exception-handling by Sphinx/Python.

So I reopen it.
