### ISSUE TITLE
Misconfigured Needflow crashes Sphinx

### ISSUE THREAD

**Issue by florianL21** [useblocks/sphinx-needs#888]
## Current behaviour
When a needflow is added that has invalid `:link_types:` configured sphinx needs crashes the sphinx build fully:
```
writing output... [100%] index
[app] emitting event: 'doctree-resolved'(<document: <section "welcome to test's documentation!"...>>, 'index')
[app] emitting event: 'build-finished'(ExtensionError("Handler <function process_creator.<locals>.process_caller at 0x0000020CD86960E0> fo

Traceback (most recent call last):

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\cmd\build.py", line 284, in build_main
    app.build(args.force_all, args.filenames)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\application.py", line 347, in build
    self.builder.build_update()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\builders\__init__.py", line 311, in build_update
    self.build(to_build,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\builders\__init__.py", line 377, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\builders\__init__.py", line 579, in write
    self._write_serial(sorted(docnames))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\builders\__init__.py", line 586, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\environment\__init__.py", line 622, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\environment\__init__.py", line 673, in apply_post_transforms
    self.events.emit('doctree-resolved', doctree, docname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function process_creator.<locals>.process_caller at 0x0000020CD86960E0> for event 'doctree-resolved' threw an exception (exception: sequence item 0: expected str instance, dict found)
```

## Expected behavior
A warning/error message is shown and sphinx does not crash:
```
WARNING: Unknown link type NON_EXISTING_LINK_TYPE in needflow needflow-index-0. Allowed values: LINKS, PARENT_NEEDS
```

## How to reproduce
* Create a new sphinx project and add sphinx needs as an extension
* Insert the following snippet into index.rst:
```rst
.. needflow:: My first needflow
   :filter: is_need
   :tags: flow_example
   :link_types: non_existing_link_type
   :show_link_names:
```
* Run `make html`

**Comment by danwos** [comment]
The problem from the crash seems to be a problem inside the error-handling itself, if a link-type is used which is not registered.
Looks like the log-function or so is not called correctly.
